### ISSUE TITLE
unscaled values

### ISSUE THREAD

**Issue by BetterWang** [eaydin/cr2fits#2]
Dear Eaydin,

As you may know there is a fork kjordahl/cr2fits which added support for unscaled pixel values.
Do you think this feature is should be considered without interpolation, i.e. with the support of "-D" for dcraw?

Thanks,
Quan

**Comment by eaydin** [comment]
Well, this is an extremely late reply, sorry for that.

I've compared several options and it seems that -D is the best to get unscaled images (The other best option was -D6jW but it seems you need the gamma curve to be set to linear for the best result). A preview is added.

I'm working on a major update in the branch named fix-3 right now and have added this feature to it.

Thanks again, and sorry for the extremely late reply :(

![saoimage ds9_033](https://cloud.githubusercontent.com/assets/1251030/26282070/2f6a1f68-3e12-11e7-893b-f6851e5a94da.png)
