### ISSUE TITLE
Feature Request for no flipping/rotation of cr2 readout and partial solution

### ISSUE THREAD

**Issue by benolry** [eaydin/cr2fits#6]
Hi,

and thank you for this script. I was trying to force that image rotation as recorded by the camera is ignored. I thought it was as simple as adding the appropriate "-t 0" option to the dcraw call that is built in lines 299 to 302 

`            self.pbm_bytes = BytesIO(subprocess.check_output(["dcraw", "-D",
                                                              "-4", "-j",
                                                              "-c", "-t 0",
                                                              self.filename]))
`

But on execution I get an error message:

`subprocess.CalledProcessError: Command '['dcraw', '-D', '-4', '-j', '-c', '-t 0', '/Users/benolry/Pictures/2018/2018-01-14 first light 40D/flat frames//_MG_9998.CR2']' returned non-zero exit status 1
Non-numeric argument to "-t"
Traceback (most recent call last):
  File "./cr2fits.py", line 523, in <module>
    cr2.convert()
  File "./cr2fits.py", line 479, in convert
    self.read_cr2()
  File "./cr2fits.py", line 302, in read_cr2
    self.filename]))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)`

Any help would be appreciated. Thanks in advance and best regards,

Ben

**Comment by eaydin** [comment]
Hello Ben,

When passing arguments to the `check_output` method of the `subprocess` module, each argument is sent as an element of tuple.

Even though you're trying to send the argument and its value, I think you're better off sending them seperately.

So your line should be like this:
```
self.pbm_bytes = BytesIO(subprocess.check_output(["dcraw", "-D", "-4", "-j", "-c", "-t", "0", self.filename]))
```
Note that I'm sending `-t` and `0` as if they're different arguments.

I haven't tested this but I think it should solve your problem.

**Comment by benolry** [comment]
Yes, this works. Thank you so much for your instant support. I have been digging through your code the whole morning to find the reason.

**Comment by eaydin** [comment]
Glad that it helped Ben. Feel free ask away any other problems you encounter through issues. Closing this one since it's resolved.
