### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by burhankhanlodhy** [eaydin/cr2fits#7]
I am trying to add it as a module inside my code in pycharm. I have added it to my code successfully as well as astropy and numpy but, I don't know how to add the dcraw file to my computer as i am using Windows 10 and the compile code you gave in instruction was for linux. Do I need to place the dcraw file somewhere? because whenever I try to run it gives me an error. `FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by aricooperdavis** [comment]
`dcraw.c` is not a python file, it is the source code for a program called [dcraw](https://en.wikipedia.org/wiki/Dcraw). You would need a c compiler to be able to compile this source code into an executable to use. You can find a pre-compiled executable (`.exe`) online if you search for "dcraw.exe", for example from [here](http://originaldll.com/file/dcraw.exe/30132.html).
